{
 "title": "SLO / Detail",
 "description": "https://sloth.dev",
 "tags": [
  "service levels",
  "sli",
  "slo",
  "sloth"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "service",
    "query": {
     "query": "label_values(slo:objective:ratio, sloth_service)"
    }
   },
   {
    "name": "slo",
    "query": {
     "query": "label_values(slo:objective:ratio{sloth_service=\"${service}\"}, sloth_slo)"
    }
   },
   { "name": "sli_window", "label": "SLI window", "query": "5m,30m,1h,2h,6h,1d,3d,4w" },
   { "name": "min_burning_rate", "label": "Min Burning rate", "query": "1" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Exceeded burning rate SLOs ",
   "type": "table",
   "description": "The SLOs that currently are burning more error budget that then available",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "slo:current_burn_rate:ratio > ${min_burning_rate}"
    }
   ]
  },
  {
   "title": "All burning rate (Filtered >${min_burning_rate}x)",
   "type": "timeseries",
   "description": "The burning rate of the all the Service SLOs",
   "gridPos": { "h": 12, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "slo:current_burn_rate:ratio > ${min_burning_rate}",
     "legendFormat": "{{sloth_id}}"
    }
   ]
  },
  { "title": "${service}/${slo}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }, "repeat": "slo" },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slo:objective:ratio{sloth_service=\"${service}\", sloth_slo=\"${slo}\"}",
     "legendFormat": "{{sloth_id}}"
    }
   ]
  },
  {
   "title": "SLI",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (max(slo:sli_error:ratio_rate${sli_window}{sloth_service=\"${service}\", sloth_slo=\"${slo}\"}) OR on() vector(0))",
     "legendFormat": "SLI"
    },
    {
     "expr": "slo:objective:ratio{sloth_service=\"${service}\", sloth_slo=\"${slo}\"}",
     "legendFormat": "Objective"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sloth_slo_info{sloth_service=\"${service}\", sloth_slo=\"${slo}\"}",
     "legendFormat": "Objective {{sloth_objective}}%"
    }
   ]
  },
  {
   "type": "stat",
   "description": "This moment burning % of the budget.",
   "gridPos": { "h": 2, "w": 7, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slo:current_burn_rate:ratio{sloth_service=\"${service}\", sloth_slo=\"${slo}\"} or on() vector(0)",
     "legendFormat": "Current burning budget %"
    }
   ]
  },
  {
   "type": "stat",
   "description": "This month remaining error budget, starts the 1st of the month and ends  28th-31st (not rolling window)",
   "gridPos": { "h": 2, "w": 7, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1-(\n  sum_over_time(\n    (\n       slo:sli_error:ratio_rate1h{sloth_service=\"${service}\",sloth_slo=\"${slo}\"}\n       * on() group_left() (\n         month() == bool vector(${__to:date:M})\n       )\n    )[32d:1h]\n  )\n  / on(sloth_id)\n  (\n    slo:error_budget:ratio{sloth_service=\"${service}\",sloth_slo=\"${slo}\"} *on() group_left() (24 * days_in_month())\n  )\n)",
     "legendFormat": "Remaining error budget (month)"
    }
   ]
  },
  {
   "type": "stat",
   "description": "A rolling window of the total period (28d) error budget remaining.",
   "gridPos": { "h": 2, "w": 7, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "slo:period_error_budget_remaining:ratio{sloth_service=\"${service}\", sloth_slo=\"${slo}\"} or on() vector(1)",
     "legendFormat": "Remaining error budget (28d window)"
    }
   ]
  },
  {
   "title": "Month error budget burn chart",
   "type": "timeseries",
   "description": "This graph shows the month error budget burn down chart (starts the 1st until the end of the month)",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1-(\n  sum_over_time(\n    (\n       slo:sli_error:ratio_rate1h{sloth_service=\"${service}\",sloth_slo=\"${slo}\"}\n       * on() group_left() (\n         month() == bool vector(${__to:date:M})\n       )\n    )[32d:1h]\n  )\n  / on(sloth_id)\n  (\n    slo:error_budget:ratio{sloth_service=\"${service}\",sloth_slo=\"${slo}\"} *on() group_left() (24 * days_in_month())\n  )\n)",
     "legendFormat": "Remaining error budget"
    },
    {
     "expr": "1 - sum_over_time(\n  (\n    (1 / (days_in_month() * 24)) *\n    (month() == bool vector(${__to:date:M}))\n  )[32d:1h]\n)",
     "legendFormat": "Ideal constant consumption"
    }
   ]
  },
  {
   "title": "Burn rate (speed) magnitude",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 23 },
   "targets": [
    {
     "expr": "slo:current_burn_rate:ratio{sloth_service=\"${service}\", sloth_slo=\"${slo}\"} > 0",
     "legendFormat": "Burn rate"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(ALERTS{sloth_service=\"${service}\", sloth_slo=\"${slo}\", sloth_severity=\"ticket\"}) OR on() vector(0)",
     "legendFormat": "Warning alert"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(ALERTS{sloth_service=\"${service}\", sloth_slo=\"${slo}\", sloth_severity=\"page\"}) or on() vector(0)",
     "legendFormat": "Critical alert"
    }
   ]
  }
 ]
}